name: "test -> build -> update lib if needed"
on:
  push:
    branches:
      - 'master'
      - 'add-release'
    tags:
      - '!**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        name: setup node
        with:
          node-version-file: '.nvmrc'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "install"
        run: npm ci --production

      - name: "test"
        run: npm run test

      - name: "build"
        run: npm run build

      - name: "check if build has changed"
        if: success()
        id: has-changes
        run: |
          echo "LIB_DIFF=$(git diff --stat --name-only  -- lib)"  >> $GITHUB_ENV

      - name: "Commit files"
        if: ${{ env.LIB_DIFF }}
        run: |
          git config --local user.email "buildaction@bot.bot"
          git config --local user.name "Build action bot"
          git commit -m "chore: build action" -a

      - name: release
        run: npm run release
